#travis configuration for coverage testing
language: c

#sudo: false # only for faster builds

install:
- cd ${TRAVIS_BUILD_DIR} && mkdir -p build 

# install latest LCOV (1.9 was failing for me) [1]

- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install

# install lcov to coveralls conversion + upload tool
- gem install coveralls-lcov


before_script: 
- cd "${TRAVIS_BUILD_DIR}/build"
- lcov --directory . --zerocounters
- cmake ..

# Compiler selection
compiler:
  - gcc


# Build steps
script: 
  make && test/test-json-packer


after_success:
- cd "${TRAVIS_BUILD_DIR}/build"
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'tests/*' '/usr/*' 'json-packer*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
#- coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls.. for a private repo using a token
- coveralls-lcov  coverage.info #for open source